# Generated by Django 5.2.14 on 2026-05-31 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='cursos/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('publicado', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('progreso', models.PositiveIntegerField(default=0)),
                ('completado', models.BooleanField(default=False)),
                ('ultima_actividad', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-ultima_actividad'],
            },
        ),
    ]
