# Generated by Django 5.2.14 on 2026-06-01 01:00

from django.db import migrations

def create_admin(apps, schema_editor):
    Usuario = apps.get_model('usuarios', 'Usuario')

    if not Usuario.objects.filter(username='admin').exists():
        Usuario.objects.create_superuser(
            username='admin',
            email='admin@aura.com',
            password='Admin123456'
        )

class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_admin),
    ]
